// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKDsV9E_Eh_4YO9HRPSPWBgJb7BEAeHfU',
    appId: '1:893106406630:web:8c7632af1e23c19d12a727',
    messagingSenderId: '893106406630',
    projectId: 'smartbites-6c50b',
    authDomain: 'smartbites-6c50b.firebaseapp.com',
    storageBucket: 'smartbites-6c50b.firebasestorage.app',
    measurementId: 'G-091E1B0HBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk1wMfQZGIUOsL6hL7FvAledBmStyWy-4',
    appId: '1:893106406630:android:10ec7b4e6dd10c1612a727',
    messagingSenderId: '893106406630',
    projectId: 'smartbites-6c50b',
    storageBucket: 'smartbites-6c50b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDQEZddgdo-a_SB7txmXhOLi2k25_29yQ',
    appId: '1:893106406630:ios:4350012718a72c9b12a727',
    messagingSenderId: '893106406630',
    projectId: 'smartbites-6c50b',
    storageBucket: 'smartbites-6c50b.firebasestorage.app',
    iosBundleId: 'com.example.proto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDQEZddgdo-a_SB7txmXhOLi2k25_29yQ',
    appId: '1:893106406630:ios:4350012718a72c9b12a727',
    messagingSenderId: '893106406630',
    projectId: 'smartbites-6c50b',
    storageBucket: 'smartbites-6c50b.firebasestorage.app',
    iosBundleId: 'com.example.proto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKDsV9E_Eh_4YO9HRPSPWBgJb7BEAeHfU',
    appId: '1:893106406630:web:a55908b09aee686112a727',
    messagingSenderId: '893106406630',
    projectId: 'smartbites-6c50b',
    authDomain: 'smartbites-6c50b.firebaseapp.com',
    storageBucket: 'smartbites-6c50b.firebasestorage.app',
    measurementId: 'G-BY0LV3MPPC',
  );
}
